CUDA_VISIBLE_DEVICES=3 python supervised_finetuning.py \
    --model_type auto \
    --model_name_or_path path_to_model \
    --train_file_dir path_to_train_file \
    --validation_file_dir path_to_validation_file \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --do_train \
    --do_eval \
    --template_name deepseek \
    --use_peft True \
    --max_train_samples -1 \
    --max_eval_samples -1 \
    --model_max_length 4096 \
    --num_train_epochs 10 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 200 \
    --eval_steps 2000 \
    --evaluation_strategy steps \
    --save_steps 2000 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 4 \
    --output_dir path_to_output_dir \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --fp16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --cache_dir ./cache
